version: '3.1'

services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: voland
      POSTGRES_PASSWORD: voland12345
      POSTGRES_DB: todo
  backend:
    build:
      context: .
    ports:
      - 8080:8080
    command: bash -c "
      ./wait-for-postgres.sh db
      && python manage.py migrate
      && python manage.py usercreate
      && python manage.py projectcreate
      && python manage.py todocreate
      && python manage.py runserver 0.0.0.0:8080
      "
    depends_on:
      - db